### ISSUE TITLE
base64 images

### ISSUE THREAD

**Issue by konsumer** [jembezmamy/morpher-js#11]
I'd like to embed base64 images, to get around cross-domain canvas issues and make ready-made components with embedded images. [Here](http://codepen.io/konsumer/pen/RaoJoq) is a non-functioning example. Alternately, being able to pass the image object would work:

```js
var img = new Image()
img.src = 'BASE64_STRING'
config.images[0].src = img
```

**Comment by jembezmamy** [comment]
You can now provide your own Image or Canvas object by calling `setImage()` method on `MorpherJS.Image` instance:

``` javascript
var morpher = new Morpher(/* some configuration */);

// setting image by URL
morpher.images[0].setSrc("images/example.png");

// setting image with CanvasImageSource type object
var myImg = new Image();
morpher.images[1].setImage(myImg);
```

**Comment by konsumer** [comment]
this is awesome. thanks!

**Comment by konsumer** [comment]
I updated [the codepen](http://codepen.io/konsumer/pen/RaoJoq) to be a k-rad emilio estavez/charlie sheen morph. Enjoy!
