### ISSUE TITLE
Use my own canvas

### ISSUE THREAD

**Issue by konsumer** [jembezmamy/morpher-js#12]
I'd like to use my own canvas for a react component. I made a non-functioning example [here](http://codepen.io/konsumer/pen/bpBKQE). It's related to #11 in that it also doesn't show the images.

**Comment by jembezmamy** [comment]
You can now provide your own canvas, by calling `setCanvas()` on `Morpher` instance:

``` javascript
var myCanvas = document.createElement("canvas");
var morpher = new Morpher();
morpher.setCanvas(myCanvas);
```

**Comment by konsumer** [comment]
Thanks!

**Comment by konsumer** [comment]
I updated [the codepen](http://codepen.io/konsumer/pen/bpBKQE) to be an awesome cheen/estavez morph. Thanks!
