### ISSUE TITLE
GUI doesn't make triangles

### ISSUE THREAD

**Issue by GirkovArpa** [jembezmamy/morpher-js#18]
In the GUI, when clicking "Export Code", you get an array of points but the triangle array is empty.

**Comment by GirkovArpa** [comment]
Made them myself with https://github.com/mapbox/delaunator

**Comment by jembezmamy** [comment]
I'm glad you've figured that out. :) In the MorpherJS GUI you have to manually connect vertices to build triangles. So Delaunator seems like a good solution to automate this process
