### ISSUE TITLE
How to animate three images

### ISSUE THREAD

**Issue by rflnogueira** [jembezmamy/morpher-js#4]
Hi, can you provide an example with 3 images?

**Comment by acedigibits** [comment]
I have a different question from example on site. i have 4 images  and then want to animate from 1st to 2nd then from 2nd to third then from 3rd to 4th, then from 4th to 1st. i tried adding 2nd to 3rd transition by using animate [1,2] but its not transitioning to 3rd image.

**Comment by jembezmamy** [comment]
These factors work like this:

```javascript
[1, 0, 0, 0] // first image
[0, 1, 0, 0] // second image
[0, 0, 1, 0] // third image
[0, 0, 0, 1] // fourth image
```

It's explained in the [parrots example](http://jembezmamy.github.io/morpher-js/demos.html).
