### ISSUE TITLE
animationComplete event?

### ISSUE THREAD

**Issue by donundeen** [jembezmamy/morpher-js#8]
Hi,
Is it possible to put some sort of event handler in the library that triggers when the animation is complete?

I'm trying to sync multiple morphs, and am finding that the timing doesn't always match what I input as morphtime, probably due to other things going on in the page slowing things down. 

I've been trying to figure out enough about how the code works to trigger and event when the animation is complete, but I'm not finding it...

thanks for this great library, btw!

**Comment by jembezmamy** [comment]
Sure, here you go:

```javascript
var morpher = new Morpher(json);

morpher.on("complete", function() {
    // animation is complete
});
```

Cheers!

**Comment by jembezmamy** [comment]
Or not, sorry, I renamed it to `animation:complete` to be more consistent with other events.
