### ISSUE TITLE
line 82, unexpected this

### ISSUE THREAD

**Issue by donundeen** [jembezmamy/morpher-js#9]
cloned new morpher, trying to compile the coffeescript and getting this:

in morpher-js/source/javascripts/morpher/lib
$ coffee --compile morpher.js.coffee
 morpher-js/source/javascripts/morpher/lib/morpher.js.coffee:82:26: error: unexpected this
    @trigger 'image:add' this, image unless params.silent
                                     ^^^^

You can also see the error going to this link:
http://jembezmamy.github.io/morpher-js/javascripts/morpher/morpher.js

Sorry, I don't know coffeescript well enough to help...

**Comment by donundeen** [comment]
I think I fixed:
diff --git a/source/javascripts/morpher/lib/morpher.js.coffee b/source/javascripts/morpher/lib/morpher.js.coffee
index a613487..0935322 100644
--- a/source/javascripts/morpher/lib/morpher.js.coffee
+++ b/source/javascripts/morpher/lib/morpher.js.coffee
@@ -79,7 +79,7 @@ class MorpherJS.Morpher extends MorpherJS.EventDispatcher
     for event, handler of @imageEvents
       image.on event, @[handler]
     @loadHandler()
-    @trigger 'image:add' this, image unless params.silent
+    @trigger 'image:add', this, image unless params.silent

   removeImage: (image) =>
     i = @images.indexOf image
@@ -87,7 +87,7 @@ class MorpherJS.Morpher extends MorpherJS.EventDispatcher
       image.off event, @[handler]
     if i != -1
       delete @images.splice i, 1
-      @trigger 'image:remove' this, image
+      @trigger 'image:remove', this, image

**Comment by jembezmamy** [comment]
Yes, you're right, I wonder how it passed in my latest build..? Never mind, it's fixed now.
